# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The very_good_analysis package provides a recommended set of lints for
# Flutter apps, packages, and plugins designed to encourage good coding practices.
# https://pub.dev/packages/very_good_analysis
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  # Exclude generated files from analysis to avoid false positives
  exclude:
    # Generated code for JSON serialization, etc.
    - "**/*.g.dart"
    # Generated code from freezed package
    - "**/*.freezed.dart"

# Formatter configuration controls how the dart format command behaves
formatter:
  # Set the line length for formatting (default in Dart is 80)
  line-length: 80
  # Makes the formatter command exit with a non-zero exit code if any changes would be made
  # Useful in CI/CD pipelines to enforce consistent formatting
  set-exit-if-changed: true