name: flutter_firebase_auth_clean_arch
description: "Flutter authentication project with Clean Architecture"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  firebase_app_check: ^0.3.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter 
  go_router: ^14.8.1
  hooks_riverpod: ^2.5.1
  intl: any

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env